use_frameworks!

platform :ios, '8.0'

target 'FSCommons_Example' do
  pod 'FSCommons', :path => '../'

  target 'FSCommons_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
